import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  wissensSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Skills',
      link: {type: 'doc', id: 'skills/index'},
      items: [{type: 'autogenerated', dirName: 'skills'}],
    },
  ],
};

export default sidebars;
